default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  user: postgres
  password: postgres

development:
  <<: *default
  database: album_music_development

test:
  <<: *default
  host: localhost
  database: db/album_music_test
  password: postgres